"use client"
import {Geist, Geist_Mono} from "next/font/google";
import "@/styles/index.css";
import "./globals.css";
// import {AntdRegistry} from "@ant-design/nextjs-registry";
import {Provider, useDispatch} from "react-redux";
import {PersistGate} from 'redux-persist/integration/react';
import {store, persistor} from "@/store";
import AppInit from "@/app/AppInit";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

// export const metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({children}) {

    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <Provider store={store}>
            <PersistGate loading={null} persistor={persistor}>
                <AppInit></AppInit>
                {children}
            </PersistGate>
        </Provider>
        </body>
        </html>
    );
}
